# XXX consider using alpine and apk add'ing curl?
image: node:16

variables:
  PACKAGE_NAME: "${CI_PROJECT_NAME}"
  MANIFEST_NAME: "module.json"
  ZIP_FILE_NAME: "${PACKAGE_NAME}-${CI_COMMIT_TAG}.zip"
  PACKAGE_BASE: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${PACKAGE_NAME}"
  PACKAGE_LATEST_BASE: "${PACKAGE_BASE/latest"
  PACKAGE_VERSION_BASE: "${PACKAGE_BASE/${CI_COMMIT_TAG}"
  PACKAGE_LATEST_MANIFEST: "${PACKAGE_LATEST_BASE}/${MANIFEST_NAME}"
  PACKAGE_LATEST_DOWNLOAD: "${PACKAGE_LATEST_BASE}/${ZIP_FILE_NAME}"
  PACKAGE_VERSION_MANIFEST: "${PACKAGE_VERSION_BASE}/${MANIFEST_NAME}"
  PACKAGE_VERSION_DOWNLOAD: "${PACKAGE_VERSION_BASE}/${ZIP_FILE_NAME}"

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/


build:
  stage: build
  script:
    - export
    - npm i
    - npx gulp updateManifestFromCITagPush
    - npx gulp packidge
    - ls -l
    - ls -l package
  artifacts:
    paths:
      - package
      - module.json
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+/'

deploy:
  stage: deploy
  image: curlimages/curl:latest
  script: |
    curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ${MANIFEST_NAME} "${PACKAGE_LATEST_MANIFEST}"
    curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ${MANIFEST_NAME} "${PACKAGE_VERSION_MANIFEST}"
    curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ${package/ZIP_FILE_NAME} "${PACKAGE_LATEST_DOWNLOAD}"
    curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ${package/ZIP_FILE_NAME} "${PACKAGE_VERSION_DOWNLOAD}"
  release:
    tag_name: '$CI_COMMIT_TAG'
    ref: '$CI_COMMIT_TAG'
    description: "**Installation:** To manually install this release, please use the following manifest URL: ${PACKAGE_VERSION_MANIFEST}"
    assets:
      links:
        # links the release to the system manifest from this CI workflow
        - name: ${MANIFEST_NAME}
          url: ${PACKAGE_VERSION_MANIFEST}
        # links the release to the zip file from this CI workflow
        - name: '$ZIP_FILE_NAME'
          url: ${PACKAGE_VERSION_DOWNLOAD}
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+/'
